#!/bin/bash
#
#	Startet den Docker Container und dann das CLI
#

export CONTAINER=neo4j01
export IMAGE=neo4j:3.0
export PORT=7474

b=`docker ps -q --filter "name=${CONTAINER}"`

if	[ "${b}" != "" ]
then
	docker stop ${b}
	docker rm ${b}
fi

docker run -d -p ${PORT}:${PORT} --name ${CONTAINER} ${IMAGE} 

