apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bigdata
  namespace: mc-b
  description: Umgebung für Kurs Big Data - https://www.eb-zuerich.ch/angebot/big-data-ueberblick.html
  tags: 
  - no-sql
  - cassandra
  - kafka
  - mongodb
  - neo4j
  - redis
  - eb
  - education
  links:
  - url: https://github.com/mc-b/bigdata
    title: Repository
    icon: github
  annotations:
    github.com/project-slug: mc-b/bigdata
    backstage.io/source-location: url:https://github.com/mc-b/bigdata
    # backstage.io/techdocs-ref: url:https://github.com/mc-b/bigdata
spec:
  type: website
  lifecycle: deprecated
  owner: group:mc-b/mc-b
