#!/bin/bash
#
#	Startet den Docker Container und dann das CLI
#

export CONTAINER=mongodb01
export IMAGE=mongodb
export CMD=mongo
export PORT=27017

b=`docker ps -q --filter "name=${CONTAINER}"`

if	[ "${b}" != "" ]
then
	docker stop ${b}
	docker rm ${b}
fi

docker run -d -p ${PORT}:${PORT} --name ${CONTAINER} ${IMAGE} 
sleep 2
docker exec -it ${CONTAINER} ${CMD}

